---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: '>=2.18.0'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: sealed-secrets-controller
  storageNamespace: flux-system
  targetNamespace: flux-system
  upgrade:
    crds: CreateReplace
