packages:
  - src/**

catalog:
  '@eslint/js': ^9.38.0
  '@tailwindcss/postcss': ^4.1.16
  '@tailwindcss/vite': 4.1.17
  '@types/node': 24.10.1
  '@vitejs/plugin-react': 5.1.0
  eslint: ^9.38.0
  postcss: ^8.5.6
  prettier: ^3.6.2
  tailwindcss: 4.1.17
  typescript: ^5.9.3
  vite: 7.1.12
  zod: 4.1.12

catalogs:
  react19:
    '@types/react': ^19.1.12
    '@types/react-dom': ^19.1.9
    react: 19.1.1
    react-dom: 19.1.1

injectWorkspacePackages: true

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@bufbuild/buf'
  - '@nestjs/core'
  - '@tailwindcss/oxide'
  - esbuild
  - protobufjs
  - unrs-resolver

overrides:
  '@types/minimatch': 5.1.2
  lightningcss: 1.30.1
  vite: 7.1.12

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss

syncInjectedDepsAfterScripts:
  - build
