apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: default
  labels:
    scrapeMetrics: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      scrapeMetrics: enabled
  template:
    metadata:
      labels:
        scrapeMetrics: enabled
        app.kubernetes.io/name: demo-app
      containers:
        - name: main
          image: docker.io/victoriametrics/demo-app:1.2
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: default
  labels:
    app.kubernetes.io/name: demo-app
spec:
  selector:
    app.kubernetes.io/name: demo-app
  ports:
    - port: 8080
      name: http
