/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authTransfersRouteImport } from './routes/(auth)/transfers'
import { Route as authSuccessRouteImport } from './routes/(auth)/success'
import { Route as authMeRouteImport } from './routes/(auth)/me'
import { Route as authDashboardRouteImport } from './routes/(auth)/dashboard'
import { Route as authStripeRefreshOnboardRouteImport } from './routes/(auth)/stripe.refresh-onboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authTransfersRoute = authTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => authRouteRoute,
} as any)
const authSuccessRoute = authSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => authRouteRoute,
} as any)
const authMeRoute = authMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => authRouteRoute,
} as any)
const authDashboardRoute = authDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authRouteRoute,
} as any)
const authStripeRefreshOnboardRoute =
  authStripeRefreshOnboardRouteImport.update({
    id: '/stripe/refresh-onboard',
    path: '/stripe/refresh-onboard',
    getParentRoute: () => authRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof authDashboardRoute
  '/me': typeof authMeRoute
  '/success': typeof authSuccessRoute
  '/transfers': typeof authTransfersRoute
  '/stripe/refresh-onboard': typeof authStripeRefreshOnboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof authDashboardRoute
  '/me': typeof authMeRoute
  '/success': typeof authSuccessRoute
  '/transfers': typeof authTransfersRoute
  '/stripe/refresh-onboard': typeof authStripeRefreshOnboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/(auth)/dashboard': typeof authDashboardRoute
  '/(auth)/me': typeof authMeRoute
  '/(auth)/success': typeof authSuccessRoute
  '/(auth)/transfers': typeof authTransfersRoute
  '/(auth)/stripe/refresh-onboard': typeof authStripeRefreshOnboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/me'
    | '/success'
    | '/transfers'
    | '/stripe/refresh-onboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/me'
    | '/success'
    | '/transfers'
    | '/stripe/refresh-onboard'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/login'
    | '/signup'
    | '/(auth)/dashboard'
    | '/(auth)/me'
    | '/(auth)/success'
    | '/(auth)/transfers'
    | '/(auth)/stripe/refresh-onboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/transfers': {
      id: '/(auth)/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof authTransfersRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/success': {
      id: '/(auth)/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof authSuccessRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/me': {
      id: '/(auth)/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof authMeRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/dashboard': {
      id: '/(auth)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authDashboardRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/stripe/refresh-onboard': {
      id: '/(auth)/stripe/refresh-onboard'
      path: '/stripe/refresh-onboard'
      fullPath: '/stripe/refresh-onboard'
      preLoaderRoute: typeof authStripeRefreshOnboardRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authDashboardRoute: typeof authDashboardRoute
  authMeRoute: typeof authMeRoute
  authSuccessRoute: typeof authSuccessRoute
  authTransfersRoute: typeof authTransfersRoute
  authStripeRefreshOnboardRoute: typeof authStripeRefreshOnboardRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authDashboardRoute: authDashboardRoute,
  authMeRoute: authMeRoute,
  authSuccessRoute: authSuccessRoute,
  authTransfersRoute: authTransfersRoute,
  authStripeRefreshOnboardRoute: authStripeRefreshOnboardRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
