apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: 1.28.2
  dependsOn:
    - name: istio-base
  values:
    global:
      istioNamespace: istio-system