apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: newt
  namespace: newt
spec:
  interval: 5m
  chart:
    spec:
      chart: newt
      sourceRef:
        kind: HelmRepository
        name: fossorial
        namespace: flux-system
      version: 1.1.0
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    newtInstances:
      - name: main
        enabled: true
        auth:
          existingSecretName: newt-cred
          keys:
            endpointKey: PANGOLIN_ENDPOINT
            idKey: NEWT_ID
            secretKey: NEWT_SECRET
