apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: secrets-operator
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: secrets-operator
      sourceRef:
        kind: HelmRepository
        name: infisical
        namespace: flux-system
